apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::545670755158:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-V4GX5TPAUYUZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::545670755158:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-03T16:00:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1445"
  uid: 2cf2665c-c1af-4464-b6b9-2d9c407c0cf2
